Add new navigation reference
shoutem/shoutem.github.io pull request #207
Opened 2021-09-23 12:03 UTC by sstimac

2021-09-24 12:03 UTC, Definitely-Not-Vlad requested changes
Requesting changes just for some grammar stuff and minor details, great work!

2021-09-27 11:36 UTC, sstimac commented on docs/extensions/tutorials/_posts/1970-01-18-NavigationStacks.md
> +ModalScreens.registerModalScreens(['shoutem.news.NewsListScreen']);
i did this intentionally, to make it more clear, but i see your point

2021-09-27 11:36 UTC, sstimac commented on docs/extensions/tutorials/_posts/1970-01-19-NavigationScreenDecorators.md
> +A screen decorator in its nature is just a simple [HoC](https://reactjs.org/docs/higher-order-components.html) that wraps your screen with additional code. Good example of this can be seen in [shoute
Link should do. I want them to open this article and read about it if they don't know it. If they do, HoC should be recognizable

2021-09-27 11:38 UTC, Definitely-Not-Vlad approved these changes

2021-09-27 11:39 UTC, merged